type: chart
builds:
  - image: samsung_cnct/cicd-tests
    context: cicd-tests
    chart: cicd-tests
    value: image.repo
    dockerContext: .
  - image: docker.io/zachpuck/kind-ci:0.1.0
    script: scripts/kind-test.sh
    shell: /bin/sh
deployments:
  - chart: cicd-tests
    timeout: 600
    retries: 2
    release: cicd-tests
prod:
  doDeploy: none
